In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.externals import joblib
import warnings
warnings.filterwarnings('ignore')

In [ ]:
data=pd.read_csv('C:/Users/DC/Downloads/agaricus-lepiota.csv')

In [ ]:
data

In [ ]:
df=pd.DataFrame(data)

In [ ]:
df.shape

In [ ]:
le=LabelEncoder()
for i in df.columns:
    df[i]=le.fit_transform(df[i].astype(str))
    

In [ ]:
df

In [ ]:
df.isnull().sum()

In [ ]:
for i in df.columns:
    plt.figure()
    plt.hist(df[i])

In [ ]:
for i in df.columns:
    plt.figure()
    sns.barplot('class',i,data=df)

In [ ]:
df.dtypes

In [ ]:
df.describe()

In [ ]:
from scipy.stats import zscore
threhold=3
z=np.abs(zscore(df))
z

In [ ]:
print(np.where(z>3))

In [ ]:
df

In [ ]:
df.skew()

In [ ]:
plt.figure(figsize=(15,20))
sns.heatmap(df.corr(),annot=True)

In [ ]:
df.corr()

In [ ]:
df

In [ ]:
data

In [ ]:
sns.distplot(df['veil-type'])

In [ ]:
df=df.drop(['veil-type'],axis=1)

In [ ]:
df

In [ ]:
df.shape

In [ ]:
x=df.iloc[:,1:23]
y=df.iloc[:,0]

In [ ]:
x.shape

In [ ]:
y.shape


In [ ]:
y=y.values.reshape(-1,1)

In [ ]:
def max_score(model):
    max_score=0
    for r_state in range(42,100):
        xtrain,xtest,ytrain,ytest=train_test_split(x,y,random_state=r_state,test_size=0.20)
        model.fit(xtrain,ytrain)
        ypred=model.predict(xtest)
        accuracy=accuracy_score(ytest,ypred)
        print('accuracy is',accuracy,'with r state',r_state)
        if accuracy>max_score:
            max_score=accuracy
            final_r_state=r_state
            print(max_score,'is max accuracy against r_state',r_state)
            print(cross_val_score(model,x,y,cv=10,scoring='accuracy').mean())

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
algo=KNeighborsClassifier()
para={'n_neighbors':[3,4,5,6,7,8,9,10]}
grid=GridSearchCV(estimator=algo,param_grid=para)
grid.fit(x,y)

print(grid.best_params_)

In [ ]:
algo=SVC()
para={'kernel':['rbf','poly','linear'],'C':[1,10]}
grid=GridSearchCV(estimator=algo,param_grid=para)
grid.fit(x,y)

print(grid.best_params_)

In [ ]:
algo=DecisionTreeClassifier()
para={'criterion':['gini','entropy']}
grid=GridSearchCV(estimator=algo,param_grid=para)
grid.fit(x,y)

print(grid.best_params_)

In [ ]:
algo=RandomForestClassifier()
para={'n_estimators':[50,100,150,200,500,1000],}
grid=GridSearchCV(estimator=algo,param_grid=para)
grid.fit(x,y)

print(grid.best_params_)

In [ ]:
lr=LogisticRegression()
dtc=DecisionTreeClassifier(criterion='gini')
rf=RandomForestClassifier(n_estimators=1000)
svc=SVC(kernel='linear',C=10)
knc=KNeighborsClassifier(n_neighbors=3)
algorithm=[lr,dtc,rf,svc,knc]

In [129]:
max_score(lr)
    
    

accuracy is 0.947076923076923 with r state 42
0.947076923076923 is max accuracy against r_state 42
0.8798658195941564
accuracy is 0.9489230769230769 with r state 43
0.9489230769230769 is max accuracy against r_state 43
0.8798658195941564
accuracy is 0.9593846153846154 with r state 44
0.9593846153846154 is max accuracy against r_state 44
0.8798658195941564
accuracy is 0.9513846153846154 with r state 45
accuracy is 0.952 with r state 46
accuracy is 0.944 with r state 47
accuracy is 0.9513846153846154 with r state 48
accuracy is 0.9452307692307692 with r state 49
accuracy is 0.939076923076923 with r state 50
accuracy is 0.947076923076923 with r state 51
accuracy is 0.9433846153846154 with r state 52
accuracy is 0.9507692307692308 with r state 53
accuracy is 0.952 with r state 54
accuracy is 0.9538461538461539 with r state 55
accuracy is 0.9464615384615385 with r state 56
accuracy is 0.9452307692307692 with r state 57
accuracy is 0.9538461538461539 with r state 58
accuracy is 0.94707692307

In [130]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,random_state=88,test_size=0.20)

In [131]:
for i in algorithm:
    i.fit(xtrain,ytrain)
    ypred=i.predict(xtest)
    accuracy=accuracy_score(ytest,ypred)
    print(accuracy_score(ytest,ypred))
    print(confusion_matrix(ytest,ypred))
    print(classification_report(ytest,ypred))

0.9612307692307692
[[806  27]
 [ 36 756]]
              precision    recall  f1-score   support

           0       0.96      0.97      0.96       833
           1       0.97      0.95      0.96       792

    accuracy                           0.96      1625
   macro avg       0.96      0.96      0.96      1625
weighted avg       0.96      0.96      0.96      1625

1.0
[[833   0]
 [  0 792]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       833
           1       1.00      1.00      1.00       792

    accuracy                           1.00      1625
   macro avg       1.00      1.00      1.00      1625
weighted avg       1.00      1.00      1.00      1625

1.0
[[833   0]
 [  0 792]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       833
           1       1.00      1.00      1.00       792

    accuracy                           1.00      1625
   macro avg       1.00      1.0

dtc and rf has the highest accuracy