In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import LabelEncoder
from scipy.stats import zscore
from sklearn.externals import joblib
import warnings
warnings.filterwarnings('ignore')

In [ ]:
data=pd.read_csv('C:/Users/DC/Downloads/titanic.csv')

In [ ]:
data

In [ ]:
df=pd.DataFrame(data)

In [ ]:
df.shape

In [ ]:
df=df.drop(['Name'],axis=1)

In [ ]:
df.shape

In [ ]:
df.dtypes

In [ ]:
le=LabelEncoder()

In [ ]:
df['Sex']=le.fit_transform(df['Sex'].astype(str))

In [ ]:
df

In [ ]:
df.dtypes

In [ ]:
df.describe()

In [ ]:
df.isnull().sum()

In [ ]:
df['Siblings/Spouses Aboard'].plot.box()

In [ ]:
df['Age'].plot.box()

In [ ]:
df['Fare'].plot.box()

In [ ]:
z=np.abs(zscore(df))

In [ ]:
print(np.where(z>3))

In [ ]:
df_new=df[(z<3).all(axis=1)]

In [ ]:
df_new.describe()

In [ ]:
df.skew()

In [ ]:
df_new.corr()

In [ ]:
plt.figure()
sns.heatmap(df_new.corr(),annot=True)

In [ ]:
df_new

In [ ]:
x=df_new.iloc[:,1:7]
y=df_new.iloc[:,0]

In [ ]:
x

In [ ]:
y.shape

In [ ]:
x.shape

In [ ]:
y=y.values.reshape(-1,1)

In [ ]:
y.shape

In [ ]:
for i in df_new.columns:
    plt.figure()
    plt.hist(df[i])

In [ ]:
for i in x.columns:
    plt.figure()
    sns.barplot(i,'Survived',data=df)

In [ ]:
se=StandardScaler()

In [ ]:
x_s=se.fit_transform(x)

In [ ]:
x

In [ ]:
x=pd.DataFrame(x_s,columns=x.columns)

In [ ]:
x

In [ ]:
def max_score(model):
    max_score=0
    for r_state in range(42,100):
        xtrain,xtest,ytrain,ytest=train_test_split(x,y,random_state=r_state,test_size=0.20)
        model.fit(xtrain,ytrain)
        ypred=model.predict(xtest)
        accuracy=accuracy_score(ytest,ypred)
        
        if accuracy>max_score:
            max_score=accuracy
            final_r_state=r_state
    print(max_score,'is max accuracy against r_state',final_r_state)
    print(cross_val_score(model,x,y,cv=10,scoring='accuracy').mean())

In [ ]:
algo=KNeighborsClassifier()
para={'n_neighbors':[3,4,5,6,7,8,9,10]}
grid=GridSearchCV(estimator=algo,param_grid=para)
grid.fit(x,y)

print(grid.best_params_)

In [ ]:
algo=SVC()
para={'kernel':['rbf','poly','linear'],'C':[1,10]}
grid=GridSearchCV(estimator=algo,param_grid=para)
grid.fit(x,y)

print(grid.best_params_)

In [ ]:
algo=DecisionTreeClassifier()
para={'criterion':['gini','entropy']}
grid=GridSearchCV(estimator=algo,param_grid=para)
grid.fit(x,y)

print(grid.best_params_)

In [ ]:
algo=RandomForestClassifier()
para={'n_estimators':[50,100,150,200,500,1000],}
grid=GridSearchCV(estimator=algo,param_grid=para)
grid.fit(x,y)

print(grid.best_params_)

In [ ]:
lr=LogisticRegression()
dtc=DecisionTreeClassifier(criterion='entropy')
rf=RandomForestClassifier(n_estimators=200)
svc=SVC(kernel='poly',C=1)
knc=KNeighborsClassifier(n_neighbors=4)
algorithm=[lr,dtc,rf,svc,knc]

In [ ]:
for i in algorithm:
    max_score(i)

In [205]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,random_state=72,test_size=0.20)
lr.fit(xtrain,ytrain)
ypred=i.predict(xtest)
accuracy=accuracy_score(ytest,ypred)
print(accuracy_score(ytest,ypred))
print(confusion_matrix(ytest,ypred))
print(classification_report(ytest,ypred))

0.8848484848484849
[[98  3]
 [16 48]]
              precision    recall  f1-score   support

           0       0.86      0.97      0.91       101
           1       0.94      0.75      0.83        64

    accuracy                           0.88       165
   macro avg       0.90      0.86      0.87       165
weighted avg       0.89      0.88      0.88       165



In [206]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,random_state=72,test_size=0.20)
dtc.fit(xtrain,ytrain)
ypred=dtc.predict(xtest)
accuracy=accuracy_score(ytest,ypred)
print(accuracy_score(ytest,ypred))
print(confusion_matrix(ytest,ypred))
print(classification_report(ytest,ypred))

0.8666666666666667
[[94  7]
 [15 49]]
              precision    recall  f1-score   support

           0       0.86      0.93      0.90       101
           1       0.88      0.77      0.82        64

    accuracy                           0.87       165
   macro avg       0.87      0.85      0.86       165
weighted avg       0.87      0.87      0.86       165



In [207]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,random_state=61,test_size=0.20)
rf.fit(xtrain,ytrain)
ypred=rf.predict(xtest)
accuracy=accuracy_score(ytest,ypred)
print(accuracy_score(ytest,ypred))
print(confusion_matrix(ytest,ypred))
print(classification_report(ytest,ypred))

0.8606060606060606
[[95 10]
 [13 47]]
              precision    recall  f1-score   support

           0       0.88      0.90      0.89       105
           1       0.82      0.78      0.80        60

    accuracy                           0.86       165
   macro avg       0.85      0.84      0.85       165
weighted avg       0.86      0.86      0.86       165



In [208]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,random_state=46,test_size=0.20)
svc.fit(xtrain,ytrain)
ypred=svc.predict(xtest)
accuracy=accuracy_score(ytest,ypred)
print(accuracy_score(ytest,ypred))
print(confusion_matrix(ytest,ypred))
print(classification_report(ytest,ypred))

0.8787878787878788
[[95 11]
 [ 9 50]]
              precision    recall  f1-score   support

           0       0.91      0.90      0.90       106
           1       0.82      0.85      0.83        59

    accuracy                           0.88       165
   macro avg       0.87      0.87      0.87       165
weighted avg       0.88      0.88      0.88       165



In [209]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,random_state=48,test_size=0.20)
knc.fit(xtrain,ytrain)
ypred=knc.predict(xtest)
accuracy=accuracy_score(ytest,ypred)
print(accuracy_score(ytest,ypred))
print(confusion_matrix(ytest,ypred))
print(classification_report(ytest,ypred))

0.8787878787878788
[[95  6]
 [14 50]]
              precision    recall  f1-score   support

           0       0.87      0.94      0.90       101
           1       0.89      0.78      0.83        64

    accuracy                           0.88       165
   macro avg       0.88      0.86      0.87       165
weighted avg       0.88      0.88      0.88       165



In [202]:
from sklearn.ensemble import GradientBoostingClassifier,AdaBoostClassifier

In [199]:
gb=GradientBoostingClassifier()

In [200]:
gb.fit(xtrain,ytrain)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [201]:
ypred=gb.predict(xtest)
accuracy=accuracy_score(ytest,ypred)
print(accuracy_score(ytest,ypred))
print(confusion_matrix(ytest,ypred))
print(classification_report(ytest,ypred))

0.8424242424242424
[[88 13]
 [13 51]]
              precision    recall  f1-score   support

           0       0.87      0.87      0.87       101
           1       0.80      0.80      0.80        64

    accuracy                           0.84       165
   macro avg       0.83      0.83      0.83       165
weighted avg       0.84      0.84      0.84       165



In [203]:
ad=AdaBoostClassifier(n_estimators=100,base_estimator=lr,algorithm='SAMME')

In [204]:
ad.fit(xtrain,ytrain)
ypred=ad.predict(xtest)
accuracy=accuracy_score(ytest,ypred)
print(accuracy_score(ytest,ypred))
print(confusion_matrix(ytest,ypred))
print(classification_report(ytest,ypred))

0.8484848484848485
[[95  6]
 [19 45]]
              precision    recall  f1-score   support

           0       0.83      0.94      0.88       101
           1       0.88      0.70      0.78        64

    accuracy                           0.85       165
   macro avg       0.86      0.82      0.83       165
weighted avg       0.85      0.85      0.84       165



lr is the best model