In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.externals import joblib
import warnings
warnings.filterwarnings('ignore')

In [ ]:
data=pd.read_csv('C:/Users/DC/Downloads/winequality-red.csv',sep=';')
data

In [ ]:
data.shape

In [ ]:
data.describe()

In [ ]:
data.dtypes


In [ ]:
df=pd.DataFrame(data)

In [ ]:
df.isnull().sum()

In [ ]:
for i in df.columns:
    plt.figure()
    plt.boxplot(df[i],)

In [ ]:
for i in df.columns:
    plt.figure()
    plt.hist(df[i],)

In [ ]:
for i in df.columns:
    plt.figure()
    sns.barplot('quality',i,data=df)

In [ ]:
df.corr()

In [ ]:
plt.figure()
sns.heatmap(df.corr(),annot=True)

In [ ]:
from scipy.stats import zscore
threhold=3
z=np.abs(zscore(df))
z

In [ ]:
print(np.where(z>3))

In [ ]:
df_new=df[(z<3).all(axis=1)]

In [ ]:
df_new

In [ ]:
for i in df.columns:
    plt.figure()
    plt.boxplot(df_new[i],)

In [ ]:
df.skew()

In [ ]:
for col in df.columns:
    if df.skew().loc[col]>0.55:
        df[col]=np.log(df[col])

In [ ]:
df_new.skew()

In [ ]:
for col in df_new.columns:
    if df_new.skew().loc[col]>0.55:
        df_new[col]=np.log(df_new[col])

In [ ]:
x1=df.iloc[:,0:11]
y1=df.iloc[:,11]
y1=y1.values.reshape(-1,1)

In [ ]:
x=df_new.iloc[:,0:11]
y=df_new.iloc[:,11]
y=y.values.reshape(-1,1)

In [ ]:
se=StandardScaler()
x_s=se.fit_transform(x)
x=pd.DataFrame(x_s,columns=x.columns)

In [ ]:
x1_s=se.fit_transform(x1)
x1=pd.DataFrame(x1_s,columns=x1.columns)

In [ ]:
def max_score(model,a,b):
    max_score=0
    for r_state in range(42,100):
        xtrain,xtest,ytrain,ytest=train_test_split(a,b,random_state=r_state,test_size=0.20)
        model.fit(xtrain,ytrain)
        ypred=model.predict(xtest)
        accuracy=accuracy_score(ytest,ypred)
        print('accuracy is',accuracy,'with r state',r_state)
        if accuracy>max_score:
            max_score=accuracy
            final_r_state=r_state
            print(max_score,'is max accuracy against r_state',r_state)
            print(cross_val_score(model,x,y,cv=10,scoring='accuracy').mean())

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
algo=KNeighborsClassifier()
para={'n_neighbors':[3,4,5,6,7,8,9,10]}
grid=GridSearchCV(estimator=algo,param_grid=para)
grid.fit(x,y)

print(grid.best_params_)

In [ ]:
algo=SVC()
para={'kernel':['rbf','poly','linear'],'C':[1,10]}
grid=GridSearchCV(estimator=algo,param_grid=para)
grid.fit(x,y)

print(grid.best_params_)

In [ ]:
algo=DecisionTreeClassifier()
para={'criterion':['gini','entropy']}
grid=GridSearchCV(estimator=algo,param_grid=para)
grid.fit(x,y)

print(grid.best_params_)

In [ ]:
algo=RandomForestClassifier()
para={'n_estimators':[50,100,150,200,500,1000],}
grid=GridSearchCV(estimator=algo,param_grid=para)
grid.fit(x,y)

print(grid.best_params_)

In [ ]:
dtc=DecisionTreeClassifier(criterion='gini')
rf=RandomForestClassifier(n_estimators=150)
svc=SVC(kernel='rbf',C=1)
knc=KNeighborsClassifier(n_neighbors=10)
algorithm=[dtc,rf,svc,knc]

In [145]:
max_score(dtc,x,y)


accuracy is 0.5463917525773195 with r state 42
0.5463917525773195 is max accuracy against r_state 42
0.47485592820028344
accuracy is 0.6494845360824743 with r state 43
0.6494845360824743 is max accuracy against r_state 43
0.47138403401039203
accuracy is 0.6323024054982818 with r state 44
accuracy is 0.6048109965635738 with r state 45
accuracy is 0.6735395189003437 with r state 46
0.6735395189003437 is max accuracy against r_state 46
0.4838119981105338
accuracy is 0.6116838487972509 with r state 47
accuracy is 0.6082474226804123 with r state 48
accuracy is 0.5945017182130584 with r state 49
accuracy is 0.6219931271477663 with r state 50
accuracy is 0.6769759450171822 with r state 51
0.6769759450171822 is max accuracy against r_state 51
0.4720736891828059
accuracy is 0.6426116838487973 with r state 52
accuracy is 0.6288659793814433 with r state 53
accuracy is 0.5979381443298969 with r state 54
accuracy is 0.570446735395189 with r state 55
accuracy is 0.563573883161512 with r state 56
acc

In [146]:
max_score(rf,x,y)

accuracy is 0.6666666666666666 with r state 42
0.6666666666666666 is max accuracy against r_state 42
0.5713934813415209
accuracy is 0.718213058419244 with r state 43
0.718213058419244 is max accuracy against r_state 43
0.5700141709966935
accuracy is 0.7044673539518901 with r state 44
accuracy is 0.7079037800687286 with r state 45
accuracy is 0.6804123711340206 with r state 46
accuracy is 0.718213058419244 with r state 47
accuracy is 0.6701030927835051 with r state 48
accuracy is 0.7353951890034365 with r state 49
0.7353951890034365 is max accuracy against r_state 49
0.5748181388757676
accuracy is 0.718213058419244 with r state 50
accuracy is 0.7285223367697594 with r state 51
accuracy is 0.6872852233676976 with r state 52
accuracy is 0.738831615120275 with r state 53
0.738831615120275 is max accuracy against r_state 53
0.5768918280585734
accuracy is 0.6907216494845361 with r state 54
accuracy is 0.6769759450171822 with r state 55
accuracy is 0.697594501718213 with r state 56
accuracy i

In [147]:
max_score(svc,x,y)

accuracy is 0.6151202749140894 with r state 42
0.6151202749140894 is max accuracy against r_state 42
0.5961974492205951
accuracy is 0.6529209621993127 with r state 43
0.6529209621993127 is max accuracy against r_state 43
0.5961974492205951
accuracy is 0.6288659793814433 with r state 44
accuracy is 0.6288659793814433 with r state 45
accuracy is 0.6391752577319587 with r state 46
accuracy is 0.6116838487972509 with r state 47
accuracy is 0.6254295532646048 with r state 48
accuracy is 0.6804123711340206 with r state 49
0.6804123711340206 is max accuracy against r_state 49
0.5961974492205951
accuracy is 0.6597938144329897 with r state 50
accuracy is 0.6426116838487973 with r state 51
accuracy is 0.5979381443298969 with r state 52
accuracy is 0.6391752577319587 with r state 53
accuracy is 0.5979381443298969 with r state 54
accuracy is 0.6048109965635738 with r state 55
accuracy is 0.5945017182130584 with r state 56
accuracy is 0.6563573883161512 with r state 57
accuracy is 0.577319587628865

In [148]:
max_score(knc,x,y)

accuracy is 0.5773195876288659 with r state 42
0.5773195876288659 is max accuracy against r_state 42
0.5541332073689184
accuracy is 0.6357388316151202 with r state 43
0.6357388316151202 is max accuracy against r_state 43
0.5541332073689184
accuracy is 0.6185567010309279 with r state 44
accuracy is 0.6116838487972509 with r state 45
accuracy is 0.5910652920962199 with r state 46
accuracy is 0.5876288659793815 with r state 47
accuracy is 0.5807560137457045 with r state 48
accuracy is 0.6288659793814433 with r state 49
accuracy is 0.6288659793814433 with r state 50
accuracy is 0.6013745704467354 with r state 51
accuracy is 0.5979381443298969 with r state 52
accuracy is 0.5910652920962199 with r state 53
accuracy is 0.6013745704467354 with r state 54
accuracy is 0.5670103092783505 with r state 55
accuracy is 0.5773195876288659 with r state 56
accuracy is 0.6323024054982818 with r state 57
accuracy is 0.5910652920962199 with r state 58
accuracy is 0.5979381443298969 with r state 59
accuracy

In [ ]:
max_score(dtc,x1,y1)

In [ ]:
max_score(rf,x1,y1)

In [ ]:
max_score(svc,x1,y1)

In [ ]:
max_score(knc,x1,y1)

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier,AdaBoostClassifier

In [ ]:
gd=GradientBoostingClassifier()

In [ ]:
max_score(gd,x,y)

In [ ]:
ad=AdaBoostClassifier(n_estimators=100,base_estimator=dtc,algorithm='SAMME')

In [ ]:
max_score(ad,x,y)

In [ ]:
ad1=AdaBoostClassifier(n_estimators=100,base_estimator=rf,algorithm='SAMME')

In [149]:
max_score(ad1,x,y)

accuracy is 0.6701030927835051 with r state 42
0.6701030927835051 is max accuracy against r_state 42
0.5741332073689183
accuracy is 0.7044673539518901 with r state 43
0.7044673539518901 is max accuracy against r_state 43
0.5707038261691072
accuracy is 0.697594501718213 with r state 44
accuracy is 0.7010309278350515 with r state 45
accuracy is 0.697594501718213 with r state 46
accuracy is 0.718213058419244 with r state 47
0.718213058419244 is max accuracy against r_state 47
0.565186584789797
accuracy is 0.6632302405498282 with r state 48
accuracy is 0.738831615120275 with r state 49
0.738831615120275 is max accuracy against r_state 49
0.5872508266414738
accuracy is 0.7250859106529209 with r state 50
accuracy is 0.7216494845360825 with r state 51
accuracy is 0.6907216494845361 with r state 52
accuracy is 0.7250859106529209 with r state 53
accuracy is 0.6941580756013745 with r state 54
accuracy is 0.6632302405498282 with r state 55
accuracy is 0.6769759450171822 with r state 56
accuracy i

In [ ]:
ad2=AdaBoostClassifier(n_estimators=100,base_estimator=svc,algorithm='SAMME')

In [ ]:
max_score(ad2,x,y)

In [ ]:
ad3=AdaBoostClassifier(n_estimators=100,base_estimator=knc,algorithm='SAMME')

Best accuracy is RF model and adaboost on rf model

In [151]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,random_state=75,test_size=0.20)
ad1.fit(xtrain,ytrain)
ypred=ad1.predict(xtest)
accuracy=accuracy_score(ytest,ypred)
print(accuracy_score(ytest,ypred))
print(confusion_matrix(ytest,ypred))
print(classification_report(ytest,ypred))

0.7353951890034365
[[  0   8   2   0   0]
 [  0 111  20   0   0]
 [  0  26  87   8   0]
 [  0   0   9  15   1]
 [  0   0   1   2   1]]
              precision    recall  f1-score   support

           4       0.00      0.00      0.00        10
           5       0.77      0.85      0.80       131
           6       0.73      0.72      0.72       121
           7       0.60      0.60      0.60        25
           8       0.50      0.25      0.33         4

    accuracy                           0.74       291
   macro avg       0.52      0.48      0.49       291
weighted avg       0.71      0.74      0.72       291



In [152]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,random_state=95,test_size=0.20)
rf.fit(xtrain,ytrain)
ypred=rf.predict(xtest)
accuracy=accuracy_score(ytest,ypred)
print(accuracy_score(ytest,ypred))
print(confusion_matrix(ytest,ypred))
print(classification_report(ytest,ypred))

0.7594501718213058
[[  0   8   2   0   0]
 [  0 105  25   0   0]
 [  0  19  94   3   0]
 [  0   0  11  21   0]
 [  0   0   1   1   1]]
              precision    recall  f1-score   support

           4       0.00      0.00      0.00        10
           5       0.80      0.81      0.80       130
           6       0.71      0.81      0.76       116
           7       0.84      0.66      0.74        32
           8       1.00      0.33      0.50         3

    accuracy                           0.76       291
   macro avg       0.67      0.52      0.56       291
weighted avg       0.74      0.76      0.75       291



RF is the best model